services:
  frontend-builder:
    container_name: frontend-builder
    image: star-burger-frontend-builder:latest
    volumes:
      - frontend_static:/output
    command: sh -c "cp -r /built-frontend/* /output/ && echo 'Frontend copied to /output'"
    restart: "no"
    networks:
      - dbnet

  starburger:
    image: starburger:latest
    container_name: starburger
    restart: always
    command: ./entrypoint.sh
    env_file:
      - .env
    networks:
      - dbnet
    volumes:
      - /var/www/starburger/staticfiles:/app/www/starburger/staticfiles
      - /var/www/starburger/media:/app/www/starburger/media
      - frontend_static:/app/www/starburger/bundles
    user: "1000:1000"
    depends_on:
      postgres:
        condition: service_healthy
      frontend-builder:
        condition: service_completed_successfully

  postgres:
    image: postgres:17-alpine
    restart: always
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks: 
      - dbnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  dbnet:
    driver: bridge

volumes:
  postgres_data:
  frontend_static: