services:

  frontend-builder:
    container_name: frontend-builder
    build:
      context: ./starburger
      dockerfile: Dockerfile.frontend
    volumes:
      - frontend_static:/output
    command: sh -c "cp -r /built-frontend/* /output/ && echo 'Frontend copied to /output'"
    restart: "no"

  nginx:
    build:
      context: ./nginx
    image: nginx:latest
    container_name: nginx_server
    networks: 
      - dbnet
    restart: always
    ports:
      - 80:80
    volumes:
      - ./starburger/staticfiles:/usr/share/nginx/html/static
      - ./starburger/media:/usr/share/nginx/html/media
      - ./starburger/logs:/app/www/starburger/logs
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - starburger
    
  starburger:
    build: 
      context: ./starburger
      dockerfile: Dockerfile.backend
    image: starburger:latest
    container_name: starburger
    restart: always
    command: ./entrypoint.local.sh 
    env_file:
      - .env
    networks:
      - dbnet
    volumes:
      - ./starburger:/app/www/starburger
      - frontend_static:/app/www/starburger/bundles
    ports:
      - "8000:8000"
    user: "1000:1000"
    depends_on:
      postgres:
        condition: service_healthy
      frontend-builder:
        condition: service_completed_successfully
   
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks: 
      - dbnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    links:
      - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres
networks:
  dbnet:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
  frontend_static: