# Generated by Django 5.2.6 on 2025-11-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_alter_orderitem_price_at_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('un', 'Необработан'), ('pr', 'В обработке'), ('sh', 'Отправлен'), ('dl', 'Доставлен')], default='un', max_length=2),
        ),
    ]
