# Generated by Django 5.2.6 on 2025-11-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('un', 'Необработан'), ('pr', 'В обработке'), ('sh', 'Отправлен'), ('dl', 'Доставлен')], default='un', max_length=2, verbose_name='Статус'),
        ),
    ]
