# Generated by Django 5.2.6 on 2025-11-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('nstd', 'Не установлен'), ('epay', 'Электронно'), ('cash', 'Наличными')], default='nstd', max_length=4, verbose_name='Тип оплаты'),
        ),
    ]
