# Generated by Django 5.2.6 on 2025-11-23 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_cooking_restaurant_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cooking_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.restaurant', verbose_name='Ресторан-исполнитель'),
        ),
        migrations.AlterField(
            model_name='restaurantmenuitem',
            name='availability',
            field=models.BooleanField(db_index=True, default=False, verbose_name='в продаже'),
        ),
    ]
