# Generated by Django 5.2.8 on 2025-11-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_alter_order_called_at_alter_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('nstd', 'Не установлен'), ('epay', 'Электронно'), ('cash', 'Наличными')], db_index=True, default='nstd', max_length=4, verbose_name='Тип оплаты'),
        ),
    ]
