# Generated by Django 5.2.8 on 2025-11-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_order_commentary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_at_order',
            new_name='fixed_price',
        ),
    ]
