# Generated by Django 5.2.8 on 2025-11-30 15:08

from django.db import migrations

def move_location_to_geolocation(apps, schema_editor):
    OldLocation = apps.get_model('foodcartapp', 'Location')
    NewLocation = apps.get_model('geolocation', 'Location')
    
    for old_loc in OldLocation.objects.all():
        NewLocation.objects.create(
            id=old_loc.id, 
            address=old_loc.address,
            latitude=old_loc.latitude,
            longitude=old_loc.longitude,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_location_remove_restaurant_address_and_more'),
        ('geolocation', '0001_initial')
    ]

    operations = [
        migrations.RunPython(move_location_to_geolocation, reverse_code=migrations.RunPython.noop),
    ]
