# Generated by Django 5.2.8 on 2025-12-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0062_remove_order_distance_to_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commentary',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
