FROM node:16-alpine

WORKDIR /app/build

COPY package*.json ./

RUN npm ci

COPY bundles-src/ ./bundles-src/

RUN npx parcel build bundles-src/index.js --dist-dir /built-frontend --public-url="./" --no-cache

RUN ls -la /built-frontend/