# Generated by Django 5.2.6 on 2025-11-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commentary',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Комментарий'),
        ),
    ]
