# Generated by Django 5.2.6 on 2025-11-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('epay', 'Электронно'), ('cash', 'Наличными')], max_length=4, null=True, verbose_name='Тип оплаты'),
        ),
    ]
