# Generated by Django 5.2.6 on 2025-11-23 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cooking_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('un', 'Необработан'), ('pr', 'Готовится'), ('sh', 'Отправлен'), ('dl', 'Доставлен')], default='un', max_length=2, verbose_name='Статус'),
        ),
    ]
