# Generated by Django 5.2.6 on 2025-11-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_order_cooking_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance_to_restaurant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='расстояние до ресторана (км)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
