# Generated by Django 5.2.6 on 2025-11-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_order_distance_to_restaurant_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, unique=True, verbose_name='Адрес')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Найдено')),
            ],
            options={
                'verbose_name': 'Кэш геокодирования',
                'verbose_name_plural': 'Кэш геокодирования',
            },
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
    ]
