# Generated by Django 5.2.8 on 2025-11-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_addresscache_alter_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время звонка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Доставлен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('un', 'Необработан'), ('pr', 'Готовится'), ('sh', 'Отправлен'), ('dl', 'Доставлен')], db_index=True, default='un', max_length=2, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='contact_phone',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='контактный телефон'),
        ),
    ]
