# Generated by Django 5.2.8 on 2025-11-30 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_auto_20251130_1808'),
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressCache',
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='geolocation.location', verbose_name='координаты адреса доставки'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restaurant', to='geolocation.location', verbose_name='местоположение'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
