# Generated by Django 5.2.8 on 2025-12-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0061_delete_addresscache_alter_order_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='distance_to_restaurant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='location',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.TextField(default='Москва', verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
