# Generated by Django 5.2.8 on 2025-12-07 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0063_alter_order_commentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена на момент заказа'),
        ),
    ]
