# Generated by Django 5.2.8 on 2025-12-07 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0064_alter_orderitem_fixed_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена на момент заказа'),
        ),
    ]
